server:
  port: 5000

logging:
  level: WARN

spring:
  datasource:
    port: 5432
    url: x
    username: x
    password: x
    max-idle: 3
    min-idle: 0
    max-active: 3
    initial-size: 0

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  thymeleaf:
    cache: false